# Load the Pickle File

In [25]:
import tensorflow as tf
from tensorflow.keras.models import load_model
import pickle
import pandas as pd
import numpy as np

In [26]:
model = load_model('model.h5')

## load the encoder and Scaler
with open('label_encoder_gender.pkl', 'rb') as file:
    label_encoder_gender=pickle.load(file)

with open('onehot_encoder_geo.pkl', 'rb') as file:
    onehot_encode_geo=pickle.load(file)

with open('Scaler.pkl', 'rb') as file:
    scalar=pickle.load(file)

In [ ]:
input_data = {
    'CreditScore' : int(input("enter your number")),
    'Geography' : input("enter your Country"),
    'Gender' : input("enter your gender"),
    'Age' : int(input("enter your age")),
    'Tenure' : int(input("enter Tenure")),
    'Balance' : int(input("enter your Balance")),
    'NumOfProducts' : int(input("enter your products")),
    'HasCrCard' : int(input("enter your HasCrCard")),
    'IsActiveNumber' : int(input("Enter your Active Number")),
    'EstimatedSalary' : int(input("enter your salary"))
}

In [27]:
input_data = {
    'CreditScore' : 600,
    'Geography' : 'France',
    'Gender' : 'Male',
    'Age' : 40,
    'Tenure' : 3,
    'Balance' : 60000,
    'NumOfProducts' : 2,
    'HasCrCard' : 1,
    'IsActiveMember' : 1,
    'EstimatedSalary' : 50000
}

In [28]:
geo_encoded=onehot_encode_geo.transform([[input_data['Geography']]]).toarray()
geo_encoded_df=pd.DataFrame(geo_encoded, columns=onehot_encode_geo.get_feature_names_out(['Geography']))
geo_encoded_df

d:\Courses\GenAI Udemy Advanced\Customer Churn Prediction Project Using ANN\venv\Lib\site-packages\sklearn\utils\validation.py:2830: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [29]:
input_df=pd.DataFrame([input_data])
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,Male,40,3,60000,2,1,1,50000

In [30]:
input_df['Gender']=label_encoder_gender.transform(input_df['Gender'])
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,1,40,3,60000,2,1,1,50000

# Concatination & Prediction

In [31]:
input_df=pd.concat([input_df.drop("Geography",axis=1), geo_encoded_df], axis=1)
input_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,1,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [32]:
input_scaled = scalar.transform(input_df)
input_scaled

array([[-0.53598516,  0.91324755,  0.10479359, -0.69539349, -0.25781119,
         0.80843615,  0.64920267,  0.97481699, -0.87683221,  1.00150113,
        -0.57946723, -0.57638802]])

In [33]:
prediction=model.predict(input_scaled)
prediction

1/1 [==============================] - 1s 567ms/step

array([[0.02764956]], dtype=float32)

In [34]:
prediction_probab=prediction[0][0]
prediction_probab

0.02764956

In [35]:
if prediction_probab>0.5:
    print("The Customer is likely to churn")
else:
    print("The customer is not likely to churn.")

The customer is not likely to churn.