In [4]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
import pickle

In [5]:
data = pd.read_csv("Churn_Modelling.csv")
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

# Preprocess the data
### Drop irrelevant columns  - RowNumber CustomerID Surname

In [6]:
data=data.drop(['RowNumber', 'CustomerId', 'Surname'],axis=1) # axis = 1 (Columns wise)
data.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

# Encode Categorical Variables

In [7]:
label_encoder = LabelEncoder()
data['Gender']=label_encoder.fit_transform(data['Gender'])
data.head(5)

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0

# ONE HOT ENCODE 'GEOGRAPHY'

In [8]:
from sklearn.preprocessing import OneHotEncoder
one_hot_encode = OneHotEncoder()

geo_encoder=one_hot_encode.fit_transform(data[['Geography']])

geo_encoder

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 10000 stored elements and shape (10000, 3)>

In [9]:
geo_encoder.toarray()

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [10]:
one_hot_encode.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [11]:
geo_encoded_df=pd.DataFrame(geo_encoder.toarray() ,columns=one_hot_encode.get_feature_names_out(['Geography']))
geo_encoded_df.head()

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0
1               0.0                0.0              1.0
2               1.0                0.0              0.0
3               1.0                0.0              0.0
4               0.0                0.0              1.0

# Combinng Columns with the original Data

In [12]:
data = pd.concat([data.drop('Geography',axis=1),geo_encoded_df],axis=1)
data.head(10)

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
5,645,1,44,8,113755.78,2,1,0,149756.71,1,0.0,0.0,1.0
6,822,1,50,7,0.00,2,1,1,10062.80,0,1.0,0.0,0.0
7,376,0,29,4,115046.74,4,1,0,119346.88,1,0.0,1.0,0.0
8,501,1,44,4,142051.07,2,0,1,74940.50,0,1.0,0.0,0.0
9,684,1,27,2,134603.88,1,1,1,71725.73,0,1.0,0.0,0.0

## Save the encoders and Sscaler

In [11]:
with open('label_encoder_gender.pkl','wb') as file:
    pickle.dump(label_encoder,file)

with open('onehot_encoder_geo.pkl','wb') as file:
    pickle.dump(one_hot_encode,file)

In [12]:
data.head(10)

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
5,645,1,44,8,113755.78,2,1,0,149756.71,1,0.0,0.0,1.0
6,822,1,50,7,0.00,2,1,1,10062.80,0,1.0,0.0,0.0
7,376,0,29,4,115046.74,4,1,0,119346.88,1,0.0,1.0,0.0
8,501,1,44,4,142051.07,2,0,1,74940.50,0,1.0,0.0,0.0
9,684,1,27,2,134603.88,1,1,1,71725.73,0,1.0,0.0,0.0

# Divide the dataset into independent and dependent features

In [13]:
x = data.drop('Exited',axis=1)

y = data['Exited']

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2, random_state=42)

scaler = StandardScaler()

x_train = scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)

In [14]:
with open('Scaler.pkl','wb') as file:
    pickle.dump(scaler,file)

# Artificial Neural Network Implementation
1 Sequential Network.  
2 Dense Layer - Defined How Much hidden layer.   
3 Activation functions - sigmoid, tanh, relu, leaky relu.  
4 Optimizer - Useful In Back propogation - Updating in the weights.  
5 Loss Function  
6 Metrics  
7 Logs - Training informstion into the folder -- Tensorbooard is used to display this logs like visualization graphs

In [14]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

In [15]:
model = Sequential([
    Dense(64,activation='relu',input_shape=(x_train.shape[1],)), #First Hidden layer connected with the input layer
    Dense(32,activation='relu'), # HL2
    Dense(1,activation='sigmoid') # output layer
])

WARNING:tensorflow:From d:\Courses\GenAI Udemy Advanced\Customer Churn Prediction Project Using ANN\venv\Lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

In [16]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                832

 dense_1 (Dense)             (None, 32)                2080

 dense_2 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

# Compiling the model 

### Note 1 : As it is binary classification problem I am using binary_crossentropy here

### Note 3 : If it is multiclassification problem the sparse_crossentropy is used

In [17]:
import tensorflow
opt = tensorflow.keras.optimizers.Adam(learning_rate=0.01)
loss=tensorflow.keras.losses.BinaryCrossentropy()
model.compile(optimizer=opt, loss=loss, metrics=['accuracy']) 

## This is the way we can initialise the optimizer and losses explicitly
# Advance - it allows us to set the our own learning rate in the optimizer.

In [18]:
model.compile(optimizer="adam", loss="binary_crossentropy", metrics=['accuracy']) 
# This is how we can use optimizer & loss via inbuilt parameters but it does not allow us to set own learning rate.

WARNING:tensorflow:From d:\Courses\GenAI Udemy Advanced\Customer Churn Prediction Project Using ANN\venv\Lib\site-packages\keras\src\optimizers\__init__.py:309: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

In [19]:
## Set up the Tensorboard
log_dir = "logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)

In [20]:
## Set up Early Stopping
early_stopping_callback=EarlyStopping(monitor='val_loss', patience=20, restore_best_weights=True)

In [21]:
#Train the model
history=model.fit(
    x_train,y_train, validation_data=(x_test, y_test), epochs=100, 
    callbacks=[tensorflow_callback, early_stopping_callback]
)

Epoch 1/100
WARNING:tensorflow:From d:\Courses\GenAI Udemy Advanced\Customer Churn Prediction Project Using ANN\venv\Lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

WARNING:tensorflow:From d:\Courses\GenAI Udemy Advanced\Customer Churn Prediction Project Using ANN\venv\Lib\site-packages\keras\src\engine\base_layer_utils.py:384: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

250/250 [==============================] - 11s 23ms/step - loss: 0.4529 - accuracy: 0.8039 - val_loss: 0.4000 - val_accuracy: 0.8260
Epoch 2/100
250/250 [==============================] - 3s 10ms/step - loss: 0.3907 - accuracy: 0.8371 - val_loss: 0.3601 - val_accuracy: 0.8495
Epoch 3/100
250/250 [==============================] - 3s 12ms/step - loss: 0.3567 - accuracy: 0.8566 - val_loss: 0.3460 - val_accuracy: 0.8545
Epoch 4/100
250/250 [==============================] - 2s 8ms/step - loss: 0.3444 - accuracy: 0.8583 - val_loss: 0.3507 - val_accuracy: 0.8535
Epoch 5/100
250/250 [==============================] - 2s 7ms/step - loss: 0.3389 - accuracy: 0.8608 - val_loss: 0.3475 - val_accuracy: 0.8580
Epoch 6/100
250/250 [==============================] - 1s 6ms/step - loss: 0.3356 - accuracy: 0.8601 - val_loss: 0.3423 - val_accuracy: 0.8580
Epoch 7/100
250/250 [==============================] - 2s 8ms/step - loss: 0.3320 - accuracy: 0.8605 - val_loss: 0.3407 - val_accuracy: 0.8615
Epoch 8/100
250/250 [==============================] - 2s 7ms/step - loss: 0.3296 - accuracy: 0.8639 - val_loss: 0.3421 - val_accuracy: 0.8610
Epoch 9/100
250/250 [==============================] - 3s 10ms/step - loss: 0.3277 - accuracy: 0.8635 - val_loss: 0.3402 - val_accuracy: 0.8590
Epoch 10/100
250/250 [==============================] - 3s 12ms/step - loss: 0.3246 - accuracy: 0.8640 - val_loss: 0.3383 - val_accuracy: 0.8605
Epoch 11/100
250/250 [==============================] - 5s 19ms/step - loss: 0.3229 - accuracy: 0.8655 - val_loss: 0.3421 - val_accuracy: 0.8600
Epoch 12/100
250/250 [==============================] - 5s 19ms/step - loss: 0.3223 - accuracy: 0.8661 - val_loss: 0.3417 - val_accuracy: 0.8630
Epoch 13/100
250/250 [==============================] - 5s 20ms/step - loss: 0.3201 - accuracy: 0.8671 - val_loss: 0.3438 - val_accuracy: 0.8560
Epoch 14/100
250/250 [==============================] - 3s 14ms/step - loss: 0.3188 - accuracy: 0.8676 - val_loss: 0.3415 - val_accuracy: 0.8645
Epoch 15/100
250/250 [==============================] - 4s 17ms/step - loss: 0.3165 - accuracy: 0.8674 - val_loss: 0.3404 - val_accuracy: 0.8575
Epoch 16/100
250/250 [==============================] - 4s 16ms/step - loss: 0.3152 - accuracy: 0.8701 - val_loss: 0.3416 - val_accuracy: 0.8595
Epoch 17/100
250/250 [==============================] - 4s 15ms/step - loss: 0.3132 - accuracy: 0.8699 - val_loss: 0.3421 - val_accuracy: 0.8605
Epoch 18/100
250/250 [==============================] - 3s 12ms/step - loss: 0.3111 - accuracy: 0.8725 - val_loss: 0.3443 - val_accuracy: 0.8620
Epoch 19/100
250/250 [==============================] - 3s 12ms/step - loss: 0.3105 - accuracy: 0.8721 - val_loss: 0.3412 - val_accuracy: 0.8660
Epoch 20/100
250/250 [==============================] - 3s 12ms/step - loss: 0.3097 - accuracy: 0.8704 - val_loss: 0.3367 - val_accuracy: 0.8620
Epoch 21/100
250/250 [==============================] - 2s 8ms/step - loss: 0.3075 - accuracy: 0.8714 - val_loss: 0.3419 - val_accuracy: 0.8660
Epoch 22/100
250/250 [==============================] - 2s 9ms/step - loss: 0.3064 - accuracy: 0.8727 - val_loss: 0.3412 - val_accuracy: 0.8645
Epoch 23/100
250/250 [==============================] - 2s 9ms/step - loss: 0.3046 - accuracy: 0.8734 - val_loss: 0.3465 - val_accuracy: 0.8640
Epoch 24/100
250/250 [==============================] - 2s 8ms/step - loss: 0.3033 - accuracy: 0.8742 - val_loss: 0.3464 - val_accuracy: 0.8635
Epoch 25/100
250/250 [==============================] - 2s 7ms/step - loss: 0.3021 - accuracy: 0.8739 - val_loss: 0.3477 - val_accuracy: 0.8600
Epoch 26/100
250/250 [==============================] - 2s 7ms/step - loss: 0.3008 - accuracy: 0.8765 - val_loss: 0.3457 - val_accuracy: 0.8630
Epoch 27/100
250/250 [==============================] - 1s 6ms/step - loss: 0.2988 - accuracy: 0.8760 - val_loss: 0.3437 - val_accuracy: 0.8635
Epoch 28/100
250/250 [==============================] - 2s 6ms/step - loss: 0.2971 - accuracy: 0.8750 - val_loss: 0.3484 - val_accuracy: 0.8605
Epoch 29/100
250/250 [==============================] - 2s 6ms/step - loss: 0.2965 - accuracy: 0.8790 - val_loss: 0.3465 - val_accuracy: 0.8610
Epoch 30/100
250/250 [==============================] - 1s 5ms/step - loss: 0.2962 - accuracy: 0.8759 - val_loss: 0.3559 - val_accuracy: 0.8530
Epoch 31/100
250/250 [==============================] - 3s 12ms/step - loss: 0.2947 - accuracy: 0.8760 - val_loss: 0.3502 - val_accuracy: 0.8565
Epoch 32/100
250/250 [==============================] - 3s 11ms/step - loss: 0.2943 - accuracy: 0.8755 - val_loss: 0.3509 - val_accuracy: 0.8620
Epoch 33/100
250/250 [==============================] - 3s 10ms/step - loss: 0.2927 - accuracy: 0.8767 - val_loss: 0.3478 - val_accuracy: 0.8585
Epoch 34/100
250/250 [==============================] - 2s 9ms/step - loss: 0.2928 - accuracy: 0.8781 - val_loss: 0.3481 - val_accuracy: 0.8640
Epoch 35/100
250/250 [==============================] - 2s 9ms/step - loss: 0.2915 - accuracy: 0.8780 - val_loss: 0.3588 - val_accuracy: 0.8550
Epoch 36/100
250/250 [==============================] - 2s 8ms/step - loss: 0.2891 - accuracy: 0.8795 - val_loss: 0.3524 - val_accuracy: 0.8605
Epoch 37/100
250/250 [==============================] - 2s 7ms/step - loss: 0.2867 - accuracy: 0.8811 - val_loss: 0.3561 - val_accuracy: 0.8635
Epoch 38/100
250/250 [==============================] - 2s 7ms/step - loss: 0.2863 - accuracy: 0.8809 - val_loss: 0.3556 - val_accuracy: 0.8625
Epoch 39/100
250/250 [==============================] - 2s 7ms/step - loss: 0.2858 - accuracy: 0.8777 - val_loss: 0.3567 - val_accuracy: 0.8645
Epoch 40/100
250/250 [==============================] - 2s 6ms/step - loss: 0.2849 - accuracy: 0.8798 - val_loss: 0.3608 - val_accuracy: 0.8580

In [23]:
# Save the model as h5 file beacuse it is compatible for keras
model.save('model.h5')

d:\Courses\GenAI Udemy Advanced\Customer Churn Prediction Project Using ANN\venv\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

In [22]:
## Load Tensorboard Extension
%load_ext tensorboard

In [23]:
%tensorboard --logdir logs/fit

Reusing TensorBoard on port 6006 (pid 17660), started 1:13:48 ago. (Use '!kill 17660' to kill it.)